# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# lint.select = ["E", "F"]
lint.ignore = ["E501", "E402", "E702", "E701", "E731"]

target-version = "py38"

[lint.per-file-ignores]
"__init__.py" = ["F403"]
"scripts/*" = ["F401"]
"mov_cli/players/__init__.py" = ["F405"]
"mov_cli/players/mpv.py" = ["F821"]